# 线上配置文件
# @author keriko
# @from keriko_admin
server:
  port: 8527
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuoj
    username: root
    password: mysql_2Kibed
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: jhkdjhkjdhsIUTYURTU_ZMx62h
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''